name: Build & testing
on:
  push:
    branches:
    - github_action_testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      ENV: "production"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build image with docker
        run: |
          docker build --build-arg ENV=$ENV --build-arg PORT=$PORT -t "todoapp" --no-cache .
      - name: Docker tag
        run: |
          docker tag todoapp:latest todothucle.azurecr.io/todoapp
