name: CI
on:
  push:
    branches:
    - github_action_testing

jobs:
  test:
    name: Unit testing
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      ENV: "test"
      DB_HOST: "localhost"
      DB_USERNAME: "todo"
      DB_NAME: "todo"
      DB_PASSWORD: "testing123password"
      DB_PORT: 5432
      HASH_KEY_PASSWORD: "testing_hash_key_password"
      TOKEN_SECRET_KEY: "testing_token_secret_key"
      TOKEN_EXPIRES_IN: "30m"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup packages
        run: |
          yarn
      - name: Run test cases
        run: |
          yarn test

  static-code-analysis:
    name: Static code analysis
    needs: test
    runs-on: ubuntu-latest
    env:
      PORT: 3001
      ENV: "test"
      DB_HOST: "localhost"
      DB_USERNAME: "todo"
      DB_NAME: "todo"
      DB_PASSWORD: "testing123password"
      DB_PORT: 5432
      HASH_KEY_PASSWORD: "testing_hash_key_password"
      TOKEN_SECRET_KEY: "testing_token_secret_key"
      TOKEN_EXPIRES_IN: "30m"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup packages
        run: |
          yarn
      - name: Run test coverage
        run: |
          yarn coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
  
  secret-scan:
    name: Secret scan
    needs: static-code-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  container-scan:
    name: Container scan
    needs: secret-scan
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/build
      - uses: Azure/container-scan@v0
        with:
          image-name: todoapp:latest
