name: main
on:
  push:
    branches:
    - github_action_testing

jobs:
  CI:
    uses: ./.github/workflows/CI.yml
    secrets: inherit
  CD:
    needs: CI
    uses: ./.github/workflows/CD.yml
    secrets: inherit